name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        postgres: [9.6, 10, 11, 12, 13]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        uses: docker/build-push-action@v2
        with:
          build-args: |
            POSTGRESQL_MAJOR_VERSION=${{ matrix.postgres }}
          tags: reedws/pglogical:${{ matrix.postgres }}
          pull: true
          push: false
