name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        postgres: [9.6, 10, 11, 12]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reedws/pglogical:${{ matrix.postgres }} --build-arg POSTGRESQL_MAJOR_VERSION=${{ matrix.postgres }}
      
